/**
 * Activity API
 * Activity Management API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelError } from './modelError';

export class Errors {
    /**
    * An identifier for the request.
    */
    'requestID'?: string;
    'errors': Array<ModelError>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "requestID",
            "baseName": "requestID",
            "type": "string"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<ModelError>"
        }    ];

    static getAttributeTypeMap() {
        return Errors.attributeTypeMap;
    }
}

