/**
 * Activity API
 * Activity Management API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Media {
    /**
    * The URL to the media content
    */
    'url': string;
    /**
    * The kind of media
    */
    'kind': Media.KindEnum;
    /**
    * The URL to a poster image
    */
    'thumbnail'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "Media.KindEnum"
        },
        {
            "name": "thumbnail",
            "baseName": "thumbnail",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Media.attributeTypeMap;
    }
}

export namespace Media {
    export enum KindEnum {
        Image = <any> 'image',
        Video = <any> 'video',
        Audio = <any> 'audio'
    }
}
